"""
Template visual QA tests — Phase 5A.

Verifies the new Phase 5A template features statically:
  - Per-word span structure is generated by scene.js
  - Pill label uses filled background (not text + dot only)
  - Beat-sync CSS variables are declared in style.css
  - Word-level clip containers (.word-wrap) are defined in style.css
  - Role-specific word animations are declared
  - ASS subtitle improvements in subtitle.py
  - Template still passes contract validator

These are static / unit-level checks that run in milliseconds.
A Playwright frame-capture smoke test is kept in a separate optional section
and is skipped if Playwright is not available.
"""
import re
from pathlib import Path

import pytest

# Paths
_TEMPLATES_DIR = Path(__file__).parent.parent / "app" / "templates"
_VIRAL_DIR     = _TEMPLATES_DIR / "viral"


# ═══════════════════════════════════════════════════════════════════════════════
# 1. Contract still passes after Phase 5A changes
# ═══════════════════════════════════════════════════════════════════════════════

def test_viral_template_still_passes_contract():
    from app.renderer.template_validator import validate_template
    result = validate_template(_VIRAL_DIR)
    assert result.ok, result.summary


# ═══════════════════════════════════════════════════════════════════════════════
# 2. scene.js — per-word stagger structure
# ═══════════════════════════════════════════════════════════════════════════════

def _scene_js() -> str:
    return (_VIRAL_DIR / "scene.js").read_text(encoding="utf-8")


def test_scene_js_builds_word_wrap_spans():
    """scene.js must produce .word-wrap > .word span structure."""
    src = _scene_js()
    assert 'word-wrap' in src, "scene.js must produce .word-wrap spans"
    assert 'class="word' in src or "class='word" in src or "class=\"word" in src, \
        "scene.js must produce .word spans"


def test_scene_js_sets_word_delay():
    """scene.js must set --word-delay CSS custom property on each word span."""
    src = _scene_js()
    assert '--word-delay' in src, "scene.js must set --word-delay on word spans"


def test_scene_js_has_beat_delay():
    """scene.js must compute beatDelay from audio intro_hit."""
    src = _scene_js()
    assert 'beatDelay' in src, "scene.js must compute beatDelay"
    assert 'intro_hit' in src, "scene.js must read intro_hit from audio direction"


def test_scene_js_sets_beat_delay_css_var():
    """scene.js must set --beat-delay CSS variable."""
    src = _scene_js()
    assert '--beat-delay' in src, "scene.js must set --beat-delay CSS variable"


def test_scene_js_sets_divider_delay():
    """scene.js must set --divider-delay to cascade after last word."""
    src = _scene_js()
    assert '--divider-delay' in src, "scene.js must set --divider-delay"


def test_scene_js_sets_subhead_delay():
    """scene.js must set --subhead-delay to cascade after divider."""
    src = _scene_js()
    assert '--subhead-delay' in src, "scene.js must set --subhead-delay"


def test_scene_js_uses_adaptive_font_table():
    """scene.js must use a word-count-based font size table."""
    src = _scene_js()
    assert 'baseSizeTable' in src, "scene.js must use adaptive font size table"


def test_scene_js_word_stagger_constant():
    """scene.js must define WORD_STAGGER constant for timing cascade."""
    src = _scene_js()
    assert 'WORD_STAGGER' in src, "scene.js must define WORD_STAGGER constant"


def test_scene_js_no_settimeout():
    """Contract: scene.js must not use setTimeout."""
    src = _scene_js()
    assert not re.search(r'\bsetTimeout\s*\(', src), "setTimeout is forbidden"


def test_scene_js_no_setinterval():
    """Contract: scene.js must not use setInterval."""
    src = _scene_js()
    assert not re.search(r'\bsetInterval\s*\(', src), "setInterval is forbidden"


def test_scene_js_signals_ready():
    """Contract: scene.js must set window.__SCENE_READY__ = true."""
    src = _scene_js()
    assert re.search(r'window\.__SCENE_READY__\s*=\s*true', src), \
        "scene.js must set window.__SCENE_READY__ = true"


# ═══════════════════════════════════════════════════════════════════════════════
# 3. style.css — Phase 5A visual features
# ═══════════════════════════════════════════════════════════════════════════════

def _style_css() -> str:
    return (_VIRAL_DIR / "style.css").read_text(encoding="utf-8")


def test_style_has_word_wrap_class():
    """.word-wrap overflow:hidden clip boundary must be defined."""
    src = _style_css()
    assert '.word-wrap' in src, "style.css must define .word-wrap clip container"


def test_style_has_word_class():
    """.word animated span must be defined."""
    src = _style_css()
    assert '#headline .word' in src or '\n.word ' in src or '\n.word{' in src, \
        "style.css must define .word animated span"


def test_style_has_word_reveal_keyframe():
    """wordReveal keyframe must be defined for word-by-word stagger."""
    src = _style_css()
    assert '@keyframes wordReveal' in src, "style.css must define @keyframes wordReveal"


def test_style_has_word_reveal_impact():
    """wordRevealImpact keyframe must exist for hook scenes."""
    src = _style_css()
    assert '@keyframes wordRevealImpact' in src, \
        "style.css must define @keyframes wordRevealImpact for hook scenes"


def test_style_has_payoff_pulse():
    """payoffPulse keyframe must exist for payoff scene glow."""
    src = _style_css()
    assert '@keyframes payoffPulse' in src, "style.css must define payoffPulse keyframe"


def test_style_label_uses_pill_background():
    """Label must use background: var(--accent) pill style (not just color)."""
    src = _style_css()
    label_block_match = re.search(r'#label\s*\{([^}]+)\}', src, re.DOTALL)
    assert label_block_match, "#label block must exist in style.css"
    label_block = label_block_match.group(1)
    assert 'background' in label_block, \
        "#label must use background (pill style), not just color: var(--accent)"
    assert 'border-radius' in label_block, \
        "#label must use border-radius for pill shape"


def test_style_has_beat_delay_var():
    """--beat-delay CSS variable must be declared."""
    src = _style_css()
    assert '--beat-delay' in src, "style.css must declare --beat-delay variable"


def test_style_has_divider_delay_var():
    """--divider-delay CSS variable must be declared."""
    src = _style_css()
    assert '--divider-delay' in src, "style.css must declare --divider-delay variable"


def test_style_has_halo_shift_keyframe():
    """haloShift keyframe must exist for micro-movement retention."""
    src = _style_css()
    assert '@keyframes haloShift' in src, "style.css must define @keyframes haloShift"


def test_style_has_hook_glow_keyframe():
    """hookGlowBurst keyframe must exist for hook scene impact."""
    src = _style_css()
    assert '@keyframes hookGlowBurst' in src, \
        "style.css must define @keyframes hookGlowBurst for hook scenes"


def test_style_hook_word_uses_impact_animation():
    """[data-role='hook'] must override word animation to wordRevealImpact."""
    src = _style_css()
    assert 'wordRevealImpact' in src, \
        "style.css must use wordRevealImpact for [data-role='hook'] words"


def test_style_payoff_word_uses_soft_animation():
    """[data-role='payoff'] must use softer wordRevealSoft animation."""
    src = _style_css()
    assert 'wordRevealSoft' in src, \
        "style.css must use wordRevealSoft for [data-role='payoff'] words"


# ═══════════════════════════════════════════════════════════════════════════════
# 4. subtitle.py — improved ASS styling
# ═══════════════════════════════════════════════════════════════════════════════

def test_subtitle_has_emphasis_style():
    """subtitle.py must define a viral_emphasis ASS style."""
    from app.renderer import subtitle as sub_mod
    import inspect
    src = inspect.getsource(sub_mod)
    assert 'viral_emphasis' in src, \
        "subtitle.py must define viral_emphasis ASS style for subtitle_emphasis scenes"


def test_subtitle_wrap_width():
    """Subtitle wrap width must be ≤ 28 chars for 9:16 readability."""
    from app.renderer.subtitle import _wrap_subtitle
    # 26-char lines max by default
    long_text = "This is a much longer subtitle line that should wrap properly here"
    wrapped = _wrap_subtitle(long_text)
    for line in wrapped.split("\\N"):
        assert len(line) <= 28, f"Wrapped line too long ({len(line)} chars): {line!r}"


def test_subtitle_generates_valid_ass(tmp_path: Path):
    """generate_ass_subtitles must produce a parseable .ass file with both styles."""
    from app.renderer.subtitle import generate_ass_subtitles
    from app.renderer.timeline import fixture_timeline
    from app.models.job import VisualDirection

    timeline = fixture_timeline(
        job_id="test-qa", keyword="test", output_path="/tmp/out.mp4"
    )

    # Inject emphasis on scene 0 to exercise viral_emphasis style
    vd = VisualDirection(subtitle_emphasis=True)
    object.__setattr__(timeline.scenes[0].props, 'visual_direction', vd)

    out = tmp_path / "subs.ass"
    generate_ass_subtitles(timeline, out)

    content = out.read_text(encoding="utf-8")
    assert "[V4+ Styles]" in content
    assert "viral_bold" in content
    assert "viral_emphasis" in content
    assert "[Events]" in content
    # Should have 5 Dialogue lines (one per scene)
    assert content.count("Dialogue:") == 5


def test_subtitle_time_format():
    """_ass_time must produce correct H:MM:SS.cc format."""
    from app.renderer.subtitle import _ass_time
    assert _ass_time(0.0)   == "0:00:00.00"
    assert _ass_time(3.5)   == "0:00:03.50"
    assert _ass_time(65.25) == "0:01:05.25"
    assert _ass_time(3661.0) == "1:01:01.00"


# ═══════════════════════════════════════════════════════════════════════════════
# 5. Optional Playwright frame smoke test (skipped if Playwright unavailable)
# ═══════════════════════════════════════════════════════════════════════════════

def _playwright_available() -> bool:
    try:
        import playwright.sync_api  # noqa: F401
        return True
    except ImportError:
        return False


@pytest.mark.skipif(not _playwright_available(), reason="Playwright not installed")
def test_viral_template_first_frame_is_not_blank(tmp_path: Path):
    """
    Render frame 0 of the viral template fixture and verify it is:
      - a valid PNG file
      - has non-zero dimensions (1080×1920 for final mode)
      - has non-trivial pixel variance (not a blank/black frame)

    This is an optional end-to-end smoke test. Skipped if Playwright is
    not installed in the current environment.
    """
    from playwright.sync_api import sync_playwright
    from app.renderer.timeline import fixture_timeline

    timeline = fixture_timeline(
        job_id="smoke-test", keyword="karen", output_path=str(tmp_path / "out.mp4")
    )
    scene = timeline.scenes[0]
    scene_duration = scene.end - scene.start
    fps = timeline.fps

    html_path = _VIRAL_DIR / "index.html"
    assert html_path.exists(), "viral/index.html must exist"

    with sync_playwright() as p:
        browser = p.chromium.launch()
        context = browser.new_context(
            viewport={"width": timeline.resolution[0], "height": timeline.resolution[1]}
        )
        page = context.new_page()

        # Inject minimal scene props
        scene_payload = {
            "index": scene.index,
            "start": scene.start,
            "end":   scene.end,
            "template": "viral",
            "role": "hook",
            "props": {
                "headline": scene.props.headline,
                "subhead":  scene.props.subhead,
                "animation_seed": scene.props.animation_seed,
                "highlight_word_indices": scene.props.highlight_word_indices,
            },
            "audio": {},
        }
        page.add_init_script(f"window.__SCENE__ = {scene_payload!r};")

        page.goto(html_path.as_uri())

        # Wait for SCENE_READY
        page.wait_for_function("window.__SCENE_READY__ === true", timeout=10_000)

        # Step to frame 0 (t=0)
        page.evaluate("""
            document.getAnimations().forEach(function(a) {
                a.currentTime = 0;
                a.pause();
            });
        """)

        frame_path = tmp_path / "frame_0000.png"
        page.screenshot(path=str(frame_path), full_page=False)

        browser.close()

    assert frame_path.exists(), "Screenshot must be saved"
    assert frame_path.stat().st_size > 5_000, \
        f"Frame PNG is suspiciously small ({frame_path.stat().st_size} bytes) — may be blank"
